name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-tomcat-app .

      - name: Push Docker image to EC2
        run: |
          docker save my-tomcat-app | bzip2 | ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} 'bunzip2 | docker load'

      - name: Run Docker container on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} 'docker stop my-tomcat-app || true && docker rm my-tomcat-app || true'
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} 'docker run -d -p 8080:8080 my-tomcat-app'
