name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-tomcat-app .

      - name: Save Docker image as tar file
        run: |
          docker save my-tomcat-app -o my-tomcat-app.tar
          chmod 644 my-tomcat-app.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "my-tomcat-app.tar"
          target: "~/my-tomcat-app.tar"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            docker load -i ~/my-tomcat-app.tar
            docker stop my-tomcat-app || true
            docker rm my-tomcat-app || true
            docker run -d -p 8080:8080 --name my-tomcat-app my-tomcat-app
